### ISSUE TITLE
Issue with bulk placing images

### ISSUE THREAD

**Issue by gourmet-source** [joonaspaakko/Batch-Mockup-Smart-Object-Replacement-photoshop-script#37]
Hi there, 
what am i doing wrong:

1. I fill in the FOlders with images, mockups and the folder to export the generated mockups to. 
![Bot](https://github.com/user-attachments/assets/d31d8959-a421-4439-9917-e49bf603d363)

2. than i click on "Process Images" and it shows me this  
![bot 2](https://github.com/user-attachments/assets/613f69fd-646e-4ffc-88a5-d43766f50383)

I used to have a script like that, that wsa opening 1 mockup, open it, place the image (resize if needed), save as JPG, than the next.

Cna't this script do it?

Thank you

**Comment by joonaspaakko** [comment]
What I'm seeing in the screenshot is not my script since mine doesn't have a dialog. I don't know how that is supposed to work.

If you want to try my script, I suggest you [download the standalone example and follow the instructions here](https://joonaspaakko.gitbook.io/batch-mockup-smart-object-replacement-jsx-photosho#option-1-use-a-project-template). Should be easy enough because as long as youreplace the files with your own in the same folders, it's just a matter of changing the mockup file name and smart object layer name in the `Batch replace example (Run this file in PS).jsx` and after that run the script.

**Comment by gourmet-source** [comment]
I'm so sorry. due to finding a proper one which suits me needs, i mixed yours up
