### ISSUE TITLE
Can we use it on our custom smart object and how to use it please help

### ISSUE THREAD

**Issue by tqmansmall** [joonaspaakko/Batch-Mockup-Smart-Object-Replacement-photoshop-script#9]
Can we use it on our custom smart object and how to use it please help

**Comment by joonaspaakko** [comment]
Yes that's what it's for.

I wrote the [documentation](https://joonaspaakko.gitbook.io/batch-mockup-smart-object-replacement-jsx-photosho/) to be just about as easy to understand as it can be, or at least that was the idea, but I supposed there are many points where one could easily get stuck. 

What are you having trouble with? 

Does it help if I point you towards this [standalone example](https://github.com/joonaspaakko/Batch-Mockup-Smart-Object-Replacement.js-Photoshop-script-standalone-example)?

You could swap the mockup file in this example with something else and  change the [settings script](https://github.com/joonaspaakko/Batch-Mockup-Smart-Object-Replacement.js-Photoshop-script-standalone-example/blob/main/Batch%20replace%20example%20(Run%20this%20file%20in%20PS).jsx) so that the `mockupPath` leads to your mockup psd and `target: '@screen',` has rhe name of the swappable smart object in the new mockup.

**Comment by joonaspaakko** [comment]
Closed for inactivity. You can still comment after its been closed.
